# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Stop and remove container
      run: docker rm --force cashflow-game-app
    
    - name: Run Dockerfile
      working-directory: CashflowGame.Web
      run: docker build . --file Dockerfile --tag cashflow-game

    - name: Clean unused images
      run: docker image prune --force

    - name: Start container
      run: docker run -d -p 7291:8080 --name cashflow-game-app cashflow-game
